[Minor] rspamc: fix crash on non-string element in `messages`
rspamd/rspamd pull request #4214
Opened 2022-07-13 11:26 UTC by fatalbanana

Lists and dictionaries can be added to the protocol response inside `messages`, e.g.

```
          task:append_message({foo = 'bar'}, 'yolo')
          task:append_message({'bar','foo'}, 'swag')
```

Currently this is causing a crash in `rspamc`.

```
(gdb) p ucl_object_tostring(cmesg)
$3 = 0x0
```

This doesn't look quite as I might have imagined it but it's better than crashing:
```
Message - yolo: object
Message - swag: array
```

2022-07-13 14:37 UTC, fatalbanana commented
the patch as currently proposed mishandles strings. :\ I'll revisit.

2022-07-14 20:01 UTC, vstakhov commented
I don't like the usage of the `ucl_object_tostring_forced` here, as it is way too bogus. For a human readable implementation I would suggest just to emit ucl object into, well, ucl. `ucl_object_tostring_forced` was designed to do something similar but in a more intrusive and state modifying way: `deconst->trash_stack[UCL_TRASH_VALUE] = ucl_object_emit_single_json (obj);`. Please note that it also emits json instead of a more logical choice of the `UCL_EMIT_CONFIG` (at least for the human readable output).

2022-07-15 10:37 UTC, fatalbanana commented
```
Message - yolo: {"foo":"bar"}
Message - swag: ["bar","foo"]
Message - barf: lol
```

looks nicer

2022-07-15 10:41 UTC, vstakhov requested changes

2022-07-15 10:41 UTC, vstakhov commented on src/client/rspamc.cxx
> +						ucl_object_emit(cmesg, UCL_EMIT_JSON_COMPACT));
We have discussed that with @citrin recently, and I would also suggest to make it in a different way.

1) When you do `ucl_object_emit` you allocate memory that is never freed and that's a memory leak
2) `cmesg` can be lengthy and not fitting into the terminal, so I suggest to call emit first, then check the length of the string and truncate it if the length is more than ~60 characters. We are talking about human readable representation after all.

2022-07-15 10:41 UTC, vstakhov commented on src/client/rspamc.cxx
> +			if (cmesg->type == UCL_STRING) {
👍

2022-07-15 10:42 UTC, vstakhov commented on src/client/rspamc.cxx
> +			if (cmesg->type == UCL_STRING) {
```suggestion
			if (ucl_object_type(cmesg) == UCL_STRING) {
```

2022-07-15 10:45 UTC, fatalbanana commented
Using `UCL_EMIT_CONFIG` as suggested:

```
Message - yolo: foo = "bar";

Message - swag: [
    "bar",
    "foo",
]
```

looks worse to me.

2022-07-15 11:01 UTC, vstakhov commented
Ok, let's go with the JSON approach, but please read my other comments.

2022-07-15 11:44 UTC, vstakhov approved these changes

2022-07-15 11:47 UTC, merged