[Conf] Add SenderScore RPBL return codes
rspamd/rspamd pull request #5077
Opened 2024-07-28 15:27 UTC by moisseev

2024-07-28 15:34 UTC, moisseev commented
@dragoangel Could you please review/test this configuration, with a particular focus on the weights?

2024-07-28 15:51 UTC, dragoangel commented
Will do, thank you

2024-07-28 17:56 UTC, dragoangel commented
Also I thinking about `noauth` thing, we already have scores for all sorts of `AUTH_NA` and so on, so I think - lets put `noauth` zero score, and where it added as part of something - do not add due to it `0.5`?

2024-07-28 18:51 UTC, dragoangel commented
Also after deeper investigation I can say that 
https://multirbl.valli.org/detail/score.senderscore.com.html has much better spam detection then https://multirbl.valli.org/detail/bl.score.senderscore.com.html

As Validity at https://knowledge.validity.com/hc/en-us/articles/20961730681243 states about 10k queries per day for free (also asking to register IPs of resolvers) - we better utilize only 1 by default, I propose enable `score.senderscore.com` by default and put `bl.score.senderscore.com` as disabled.

2024-07-29 15:38 UTC, dragoangel requested changes

2024-07-29 16:31 UTC, moisseev commented on conf/modules.d/rbl.conf
>        symbol = "RBL_SENDERSCORE";
I understand the reasoning behind `RBL_SENDERSCORE_UNKNOWN`. However, in my opinion, it’s better to keep `RBL_SENDERSCORE` without the `_UNKNOWN` suffix to stay consistent with the naming conventions used for other RBLs.

What do you think?

2024-07-29 17:29 UTC, merged